# Generated by Django 3.2.2 on 2021-05-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_auto_20210512_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
